image: chef/chefdk

variables:
  CHEF_LICENSE: "accept"

stages:
  - verify
  - tests
  - build
  - deploy

linter:
  stage: verify
  script: 
    - delivery local lint

unit:
  stage: tests
  script:
    - delivery local unit

integration:
  stage: tests
  script:
    - echo "Integrational test - look at kitchen.yml"

build:
  stage: build
  before_script:
    - git config user.mail "you@examplec.om"
    - git config user.name "You"
  script:
    - echo "Building configuration..."
    - git tag -a "v1.0.0"


deploy:
  stage: deploy
  script: echo "Deploying configuration but I dont have Chef server...;)"
  when: manual