image: chef/chefdk

variables:
  CHEF_LICENSE: "accept"

stages:
  - verify
  - test
  - build
  - deploy

linter:
  stage: verify
  script: 
    - delivery local lint

unit:
  stage: test
  script:
    - delivery local unit

functional:
  stage: test
  image: dokken/centos-7
  script:
    - echo "Functional test"
    - kitchen test -d always -c 3

build:
  stage: build
  script: echo "Building the app"

deploy:
  stage: deploy
  script: echo "Deploying the app"
  when: manual