image: chef/chefdk

variables:
  CHEF_LICENSE: "accept"

stages:
  - verify
  - tests
  - build
  - deploy

linter:
  stage: verify
  script: 
    - delivery local lint

unit:
  stage: tests
  script:
    - delivery local unit

integration:
  stage: tests
  script:
    - echo "Integrational test - look at kitchen.yml"

build:
  stage: build
  before_script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "pu5zkin_bot"
  script:
    - echo "Building configuration..."
    - git tag -a "v1.0.0" -m "new version"
    - git push --tags https://pu5zkin_bot:${PERSONAL_ACCESS_TOKEN}@gitlab.com/stanislaw.kuich/pu5zkin_dhcpd.git


deploy:
  stage: deploy
  script: echo "Deploying configuration but I dont have Chef server...;)"
  when: manual